---
- name: 'Install required packages'
  community.general.opkg:
    name: diffutils
    state: present

- name: 'Create /usr/local/sbin directory'
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - '/usr/local/'
    - '/usr/local/sbin/'

- name: 'Add /usr/local/sbin to $PATH'
  ansible.builtin.lineinfile:
    path: '/etc/profile'
    line: 'PATH="$PATH:/usr/local/sbin"'
    insertafter: 'export PATH='
    create: false
    state: present

- name: 'Install maintenance scripts'
  ansible.builtin.copy:
    dest: '/usr/local/sbin/'
    src: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - config-update.sh
    - opkg-predict-size.sh
    - pkg-stats.sh

- name: 'Keep maintenance scripts on system upgrades'
  ansible.builtin.lineinfile:
    path: '/etc/sysupgrade.conf'
    line: "{{ item.file }}"
    state: present
  loop:
    - file: '/usr/local/sbin/config-update.sh'
    - file: '/usr/local/sbin/opkg-predict-size.sh'
    - file: '/usr/local/sbin/pkg-stats.sh'
    - file: '/root/.profile'
      when: "{{ openwrt_maintenance_scripts_pkg_stats_on_login | bool }}"
  loop_control:
    label: "{{ item.file }}"
  when: "item.when | default(true) | bool"

- name: 'Show package stats on login'
  ansible.builtin.lineinfile:
    path: '/root/.profile'
    line: 'pkg-stats.sh && echo'
    insertafter: EOF
    create: true
    owner: root
    group: root
    mode: '0644'
    state: "{{ openwrt_maintenance_scripts_pkg_stats_on_login | bool | ternary('present', 'absent') }}"
